services:
  api:
    build:
      context: ../
      dockerfile: ./deployments/api/Dockerfile
    image: zelawat27/test_api
    hostname: api
    ports:
      - "8090:8090"
    networks:
      - api_net
    environment:
      - env=local
      - INGRESS_URL=ingress:8080
    restart: on-failure
    depends_on:
      - minio
      - mysql
      - message
      - ingress

  model:
    build:
      context: ../
      dockerfile: ./deployments/model/Dockerfile
    image: zelawat27/test_model
    hostname: model
    expose:
      - "8090"
    networks:
      - api_net
    environment:
      - env=local
    restart: on-failure
    depends_on:
      - minio
      - mysql
      - message
      - ingress

  ingress:
    build:
      context: ../
      dockerfile: ./deployments/ingress/Dockerfile
    image: zelawat27/test_ingress
    hostname: ingress
    networks:
      - api_net
    expose:
      - "8080"
    environment:
      - env=local
      - MINIO_URL=minio:9000
      - MESSAGE_URL=message:4222
    restart: on-failure
    depends_on:
      - minio
      - mysql
      - message

  mysql:
    hostname: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ../configs/db:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    networks:
      - api_net

  minio:
    hostname: minio
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DEFAULT_BUCKETS: "image"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio/data:/bitnami/minio/data
    networks:
      - api_net

  message:
    hostname: message
    image: nats-streaming:linux
    ports:
      - "4223:4223"
      - "8223:8223"
    networks:
      - api_net

networks:
  api_net:
