services:
  api:
    build:
      context: ../
      dockerfile: ./deployments/api/Dockerfile
    hostname: api
    ports:
      - "8080:8080"
    networks:
      - api_net
    restart: on-failure
  mysql:
    hostname: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ../configs/db:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    networks:
      - api_net

networks:
  api_net:
