# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image/test.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google import annotations_pb2 as google_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10image/test.proto\x12\x05image\x1a\x18google/annotations.proto\"/\n\x0cHelloRequest\x12\x1f\n\x0binput_field\x18\x01 \x01(\x0cR\ninputField\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2R\n\x07Greeter\x12G\n\x08SayHello\x12\x13.image.HelloRequest\x1a\x11.image.HelloReply\"\x11\x82\xd3\xe4\x93\x02\x0b\"\x06/image:\x01*(\x01\x42{\n\tcom.imageB\tTestProtoP\x01Z/github.com/NamanZelawat/go_test_api/proto/image\xa2\x02\x03IXX\xaa\x02\x05Image\xca\x02\x05Image\xe2\x02\x11Image\\GPBMetadata\xea\x02\x05Imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image.test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.imageB\tTestProtoP\001Z/github.com/NamanZelawat/go_test_api/proto/image\242\002\003IXX\252\002\005Image\312\002\005Image\342\002\021Image\\GPBMetadata\352\002\005Image'
  _globals['_GREETER'].methods_by_name['SayHello']._options = None
  _globals['_GREETER'].methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\013\"\006/image:\001*'
  _globals['_HELLOREQUEST']._serialized_start=53
  _globals['_HELLOREQUEST']._serialized_end=100
  _globals['_HELLOREPLY']._serialized_start=102
  _globals['_HELLOREPLY']._serialized_end=140
  _globals['_GREETER']._serialized_start=142
  _globals['_GREETER']._serialized_end=224
# @@protoc_insertion_point(module_scope)
