# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/image/test.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.google import annotations_pb2 as proto_dot_google_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/image/test.proto\x12\x05image\x1a\x1eproto/google/annotations.proto\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2Z\n\x07Greeter\x12O\n\x08SayHello\x12\x13.image.HelloRequest\x1a\x11.image.HelloReply\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/example/echo:\x01*B{\n\tcom.imageB\tTestProtoP\x01Z/github.com/NamanZelawat/go_test_api/proto/image\xa2\x02\x03IXX\xaa\x02\x05Image\xca\x02\x05Image\xe2\x02\x11Image\\GPBMetadata\xea\x02\x05Imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.image.test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.imageB\tTestProtoP\001Z/github.com/NamanZelawat/go_test_api/proto/image\242\002\003IXX\252\002\005Image\312\002\005Image\342\002\021Image\\GPBMetadata\352\002\005Image'
  _globals['_GREETER'].methods_by_name['SayHello']._options = None
  _globals['_GREETER'].methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/example/echo:\001*'
  _globals['_HELLOREQUEST']._serialized_start=65
  _globals['_HELLOREQUEST']._serialized_end=99
  _globals['_HELLOREPLY']._serialized_start=101
  _globals['_HELLOREPLY']._serialized_end=139
  _globals['_GREETER']._serialized_start=141
  _globals['_GREETER']._serialized_end=231
# @@protoc_insertion_point(module_scope)
